---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-state-metrics
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  chart:
    spec:
      chart: kube-state-metrics
      version: 5.24.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 15s
  values: {}
