---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paramstore-secretstore
spec:
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  chart:
    spec:
      chart: ./flux/helm/cluster-secretstore
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 15s
  values:
    region: us-east-2
    auth:
      secretRef:
        accessKeyIDSecretRef:
          name: external-secrets-aws-secret
          key: aws_access_key_id
          namespace: external-secrets
        secretAccessKeySecretRef:
          name: external-secrets-aws-secret
          key: aws_secret_access_key
          namespace: external-secrets
